import java.awt.Color;
import javax.swing.JOptionPane;

public class Juego2 extends javax.swing.JFrame {

    JFigura jfa = new JFigura();
    JFigura jfb = new JFigura();
    JFigura jfc = new JFigura();
    public Juego2() {
        initComponents();
           this.setLocationRelativeTo(null);
          setTitle("GIRO DE ORO");
        
        jFigA.add(jfa);
        jFigB.add(jfb);
        jFigC.add(jfc);
        
        lbEstado.setText("");              
        repaint();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFigB = new javax.swing.JPanel();
        jFigA = new javax.swing.JPanel();
        jFigC = new javax.swing.JPanel();
        lbBoton = new javax.swing.JButton();
        lbEstado = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbCredito = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbApuesta = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jFigBLayout = new javax.swing.GroupLayout(jFigB);
        jFigB.setLayout(jFigBLayout);
        jFigBLayout.setHorizontalGroup(
            jFigBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jFigBLayout.setVerticalGroup(
            jFigBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jFigB, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));

        javax.swing.GroupLayout jFigALayout = new javax.swing.GroupLayout(jFigA);
        jFigA.setLayout(jFigALayout);
        jFigALayout.setHorizontalGroup(
            jFigALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jFigALayout.setVerticalGroup(
            jFigALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jFigA, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        javax.swing.GroupLayout jFigCLayout = new javax.swing.GroupLayout(jFigC);
        jFigC.setLayout(jFigCLayout);
        jFigCLayout.setHorizontalGroup(
            jFigCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jFigCLayout.setVerticalGroup(
            jFigCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jFigC, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, -1, -1));

        lbBoton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbBoton.setText("EMPEZAR");
        lbBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbBotonActionPerformed(evt);
            }
        });
        getContentPane().add(lbBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, -1, -1));

        lbEstado.setText("jLabel2");
        getContentPane().add(lbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 270, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CREDITO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, -1, -1));

        lbCredito.setFont(new java.awt.Font("Yu Gothic", 1, 13)); // NOI18N
        lbCredito.setForeground(new java.awt.Color(255, 204, 204));
        lbCredito.setText("10000");
        getContentPane().add(lbCredito, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 110, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("APUESTA");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, -1, -1));

        lbApuesta.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbApuesta.setForeground(new java.awt.Color(255, 204, 204));
        lbApuesta.setText("100");
        getContentPane().add(lbApuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setText("Menú principal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, -1, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondo3.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbBotonActionPerformed

     lbEstado.setText("");
    String apuestaText = lbApuesta.getText();
    String creditoText = lbCredito.getText();

    if (!apuestaText.isEmpty() && !creditoText.isEmpty()) {
        int apuesta = Integer.parseInt(apuestaText);
        int credito = Integer.parseInt(creditoText);

        if (apuesta <= credito) {
            lbBoton.setEnabled(false);

            PlayWorker playWorkerA = new PlayWorker(jfa);
            PlayWorker playWorkerB = new PlayWorker(jfb);
            PlayWorker playWorkerC = new PlayWorker(jfc);

            Thread threadA = new Thread(playWorkerA);
            Thread threadB = new Thread(playWorkerB);
            Thread threadC = new Thread(playWorkerC);

            threadA.start();
            threadB.start();
            threadC.start();

            try {
                threadA.join();
                threadB.join();
                threadC.join();
            } catch (InterruptedException e) {
                e.printStackTrace();
            }

            int val1 = playWorkerA.getValue();
            int val2 = playWorkerB.getValue();
            int val3 = playWorkerC.getValue();

            boolean result = val1 == val2 && val2 == val3;

            // Actualiza la interfaz según el resultado del juego
            if (result) {
                lbCredito.setText(String.valueOf(credito + apuesta));
                lbEstado.setForeground(Color.yellow);
                lbEstado.setText("¡GANASTE!");
            } else {
                lbCredito.setText(String.valueOf(credito - apuesta));
                lbEstado.setForeground(Color.red);
                lbEstado.setText("¡PERDISTE!");
            }

            lbBoton.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(this, "Crédito insuficiente!");
        }
    } else {
        JOptionPane.showMessageDialog(this, "Ingrese valores válidos para apuesta y crédito.");
    }

    }//GEN-LAST:event_lbBotonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Menu newframe =new Menu();
   newframe.setVisible(true);
   this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
   
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jFigA;
    private javax.swing.JPanel jFigB;
    private javax.swing.JPanel jFigC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbApuesta;
    private javax.swing.JButton lbBoton;
    private javax.swing.JLabel lbCredito;
    private javax.swing.JLabel lbEstado;
    // End of variables declaration//GEN-END:variables
}
